### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by DietShasta** [bmc0/dsp#1]
I'm not sure if this is really an issue or just a "I can't figure this out" post, but I can't seem to get this to work on my raspberry pi.

Initially I tried installing dsp without the cli tool but it seemed like no dsp effects was happening at all. I lowered the gain in the config file to -10 just so it could be obvious but still sounded the same.

I installed the dsp cli. I use alsa for playback. My i2s dac is hw:0. I then run this command:

```
dsp file.wav -ot alsa -e s16 hw:0 lowshelf 60 0.5 +4.0
```

but i'm getting this error:

```
dsp: error: failed to open input: file.wav
```

file.wav does exist in the folder i'm running cli.

Thank you!

**Comment by bmc0** [comment]
Please post the contents of `~/.config/ladspa_dsp/config` and `~/.asoundrc`, as well as the output of `./configure`.

**Comment by DietShasta** [comment]
I feel like I followed the steps pretty well, but who knows.

./configure:

```
enabled dsp
[dsp] disabled sndfile.o (sndfile)
[dsp] disabled ffmpeg.o (libavcodec libavformat libavutil)
[dsp] disabled resample.o fir.o (fftw3)
[dsp] enabled alsa.o (alsa)
[dsp] disabled ao.o (ao)
[dsp] disabled mp3.o (mad)
[dsp] disabled pulse.o (libpulse-simple)
enabled ladspa_dsp
[ladspa_dsp] disabled fir.o (fftw3)
```

~/.config/ladspa_dsp/config:

```
effects_chain=gain -10.0 eq 67.7 2.0 1.3 eq 140 1.0 -2.0 eq 345 0.3 -2.9 eq 675 3.0 2.8 eq 870 3.0 -1.9 eq 1235 2.0 -5.1 eq 1785 6.0 -1.1 eq 2235 4.0 1.3 eq 3080 4.0 -1.2 eq 4500 2.0 2.0 eq 6300 2.0 -3.4 eq 7000 2.5 -2.8 eq 9000 0.3 -2.2 eq 9700 3.0 -1.7 eq 14000 0.8 -2.5
```

~/.asoundrc:

```
pcm.dsp {
    type plug
    slave {
        format FLOAT
        rate unchanged
        channels unchanged
        pcm {
            type ladspa
            playback_plugins [{
                label "ladspa_dsp"
            }]
            slave.pcm {
                type plug
                slave {
                    pcm "hw:0"
                    rate unchanged
                    channels unchanged
                }
            }
        }
    }
}

pcm.!default {
    type copy
    slave.pcm "dsp"
}

```

**Comment by bmc0** [comment]
The CLI program uses external libraries for all device and file I/O (except raw PCM files). For the sake of configurability, none of the libraries used for device or file I/O are _required_ dependencies, but the program isn't very useful without some of them. To play a wav file you'll need to install either libsndfile or ffmpeg (or both...) and rebuild (run `make distclean` first to force it to reconfigure). Make sure the configure script says "enabled" on the sndfile.o and/or ffmpeg.o lines.

Regarding the ladspa_dsp and alsa configuration, everything looks fine to me. What program are you using for music playback? Make sure that it is configured to use either `default` or `dsp` for the alsa device. If it is using `hw:0` or anything else, its output will not be processed by the plugin.

**Comment by DietShasta** [comment]
Does this mean if i dont' use the CLI program I don't have to worry about any of the other dependencies? If I run the barebones version, I should be able to get the dsp working?

I will be using squeezelite and shairport-sync to play music. When I set squeezelite to look at default, it seems like it would ignore my settings. I changed the device to hw:1 and it would still play through hw:0. I also tried putting the .asoundrc settings into /etc/asound.conf. This strangely actually did something. It made squeezelite not want to start. I removed asound.conf and just reverted back to .asoundrc and chose "dsp" as the device it should play through, and that prevented squeezelite from starting also. It seems like that default in .asoundrc is being superceded by another settings file and ignoring it.

So I think squeezelite is now actually trying to play through dsp, but now it's preventing squeezelite from starting up.

I justed tested shairport-sync. Shairport-sync will start, but when I send music to it, nothing plays. I can see that the card shows nothing is even going to it using cat /proc/asound/card0/pcm0p/sub0/hw_params

**Comment by bmc0** [comment]
> Does this mean if i dont' use the CLI program I don't have to worry about any of the other dependencies? If I run the barebones version, I should be able to get the dsp working?

Yes.

It seems that there is an error in my instructions. I figured that alsa would set the LADSPA plugin path to  `/usr/lib/ladspa` by default since that is the standard location for LADSPA plugins, but it doesn't, so alsa can't find the plugin. To fix this, insert `path "/usr/lib/ladspa"` under the `type ladspa` line:

```
...
pcm {
    type ladspa
    path "/usr/lib/ladspa"
    playback_plugins [{
...
```

I'll update the wiki page in a minute.

Make sure you put the configuration files in the correct home directory (I don't know what user squeezelite and shairport-sync might be running as), or your playback programs won't find them.

**Comment by DietShasta** [comment]
Funnily, before seeing your reply, I was looking at another website that showed that the .asoundrc file includes a path, so I added that in. This allowed me to aplay the wave file to dsp.

Both squeezelite and shairport-sync run as root, but i kept the config file in my home/pi folder. I just tried moving over the config file to /root/.config/ladspa_dsp/config but I still can't seem to get the two apps to play. I also tried moving .asoundrc to /root/.asoundrc.

**Comment by bmc0** [comment]
You could try running squeezelite or shairport-sync as a normal user. Perhaps the config files are not being loaded for some reason. Unfortunately, without some debug output from squeezelite and/or shairport-sync, I'm not sure what else to suggest.

**Comment by bmc0** [comment]
Ladspa_dsp will print some information (config file path, effects chain, and I/O buffer size) if you set the `LADSPA_DSP_LOGLEVEL` environment variable to `VERBOSE`.

**Comment by DietShasta** [comment]
I made some more progress. Shairport-sync now works. I had to refer to the device in quotes. 
Probably have to do something similar to squeezelite. I think i'll try adding the pcm.!default lines to the .asoundrc in /root. 

I think everything is set up correctly on the dsp / ladspa side, so that's good. Thank you! I'll let you know if the default works in /root

Incidentally, dsp/ladspa uses about 25% cpu on a raspberry pi a+.

**Comment by DietShasta** [comment]
After wrestling with the squeezelite init.d script found off the web, I had to revert to a simpler less fancy one to finally get it to work.

I wondered how dsp/ladspa would handle squeezelite because squeezelite hogs the alac device continuously even when not playing music. It releases the alac device once the player is in the "off" state. Anyways, I see continuous 30% cpu usage when not playing and about 38% when playing depending on the file.

**Comment by bmc0** [comment]
Good to know that you got it working.

> squeezelite hogs the alac device continuously even when not playing music.

(I'm assuming you mean "alsa" here) Unfortunately some programs do this.
