### ISSUE TITLE
channel mismatch: channels=1 impulse_channels=2

### ISSUE THREAD

**Issue by gorzelak** [bmc0/dsp#12]
Hi,

I have a problem with FIR filter as follows:

Playing WAVE '/nas/wav/msplaysweep.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
dsp: fir: error: channel mismatch: channels=1 impulse_channels=2
dsp: error: failed to initialize effect: fir

As you can see, my filter has two channels and the WAV I'm trying to play also has two channels. Somehow there is a fir filter error saying that my WAV is mono and can not be processed? Am I reading the error message correctly?

**Comment by bmc0** [comment]
By default, the LADSPA plugin is mono. For multichannel audio, the host creates multiple instances of the plugin and runs each channel through its own plugin instance. If you set the number of input and output channels to 2 in the ladspa_dsp config file, the host will send both channels through the same plugin instance:

```
input_channels=2
output_channels=2
effects_chain=your_effects_chain
```

If you're wondering why the number of channels is not automatically set, the LADSPA API does not provide any way for the host to tell the plugin how many channels the audio stream has.

**Comment by gorzelak** [comment]
Thank you Michael. My problem is solved :-)

niedz., 17.01.2016 o 06:08 użytkownik Michael Barbour <
notifications@github.com> napisał:
