### ISSUE TITLE
Use pulse as input

### ISSUE THREAD

**Issue by AndrewBelt** [bmc0/dsp#13]
Is it possible to use pulseaudio as an input while also using pulseaudio as an output? I don't understand the input type syntax. Would something like `dsp -t pulse <effects>` work?

**Comment by bmc0** [comment]
You have to give a source name too. "default" selects the server default, so `dsp -t pulse default <effects>` should work.

**Comment by bmc0** [comment]
You'll also need to set the number of channels to 2 if you want stereo: `dsp -t pulse -c 2 default <effects>`.

**Comment by AndrewBelt** [comment]
Fantastic! I didn't think this was possible, but it works perfectly. It is much easier to use dsp as a background daemon and Pulseaudio/pavucontrol to route audio through dsp's inputs/outputs than load Pulseaudio's LADSPA module for dsp's plugin form in my opinion.

This makes dsp a key component in FIR filtering of audio output for room correction.
