### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by TheGuardianWolf** [bmc0/dsp#15]
Hey, mind if I publish an AUR package to install dsp? I'm currently using this as an equalizer on Linux based on your wiki guide (works pretty well).

**Comment by bmc0** [comment]
There already is an AUR package, actually: https://aur.archlinux.org/packages/dsp-git

Currently there are a couple problems with it (see my comment on the linked page). Hopefully the maintainer will fix them soon.

**Comment by TheGuardianWolf** [comment]
Hmm.. okay, not sure how I didn't see that when I was searching.

I've built my own PKGBUILD as well a while back, guess I can throw that out now.

On an unrelated note, do you know how to swap audio channels in stereo mode? I've been looking to do this since my earphones can be put on in reverse.

**Comment by bmc0** [comment]
The remix effect can do this: `remix 1 0`.

Edit: If you're using dsp as a LADSPA plugin, you need to make sure you're running both channels through the same instance of the plugin in order for this to work.

**Comment by TheGuardianWolf** [comment]
Thanks, that should do it on my PC. Now I just gotta do it on my Android phone too. I'll close this issue now
