### ISSUE TITLE
Effects samples

### ISSUE THREAD

**Issue by arjunmenon** [bmc0/dsp#18]
Hey man
I was able to successfully include this in RPi3 and test it with gmediarender. Installing them was straight forward!

Four things I like to know
1. Is there some doc, or you can give an example, which lists different types of sample effects for equalization _(rock, pop, classical, etc)_ and reverb _(hallway, concert, living room, etc)_? This would be great to begin and **then** understanding/playing with them?

2. For mono output, I [added this](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=33431) in addition to what was described in the docs for `asound.rc`. It fails to output mono though.

> `remix 0,1 2,3` mixes input channels 0 and 1 into output channel 0, and input channels 2 and 3 into output channel 1

How does mixing 2,3 output to 1? Shouldn't it output to 2 if going by the pattern? I can't understand partly because I am failing to hear them. I simply tried `remix -`. Input is simple stereo. Required is mono from from either channel.

```
pcm.card1 {
  type hw
  card 0
}

ctl.card1 {
  type hw
  card 0
}

pcm.monocard {
  slave.pcm card0
  slave.channels 2
#  type plug
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

ctl.monocard {
  type hw
  card 0
}

pcm.!default monocard
```

3. For `ffmpeg` where is it specifically used? General audio playback works without it just fine.

4. There is a type of DSP referred to as Psychoacoustic bass boost. It just amplifies harmonics below the resonant frequency of the speaker, which is generally set in the software. Its a good type of bass boost without affecting the excursion of the driver. Since it simply filter out the fundamentals.

Therefore, are there settings to just extract harmonics, say before, 100 hz and apply a gain to them.
Like for 50Hz I run a filter and get all its even harmonics, discard the fundamental which is 50hz.  and apply a gain to all even harmonics. 
Repeat with 51, 52, etc.

**Comment by bmc0** [comment]
1. I would recommend that you just look up how to use a parametric equalizer. There's quite a lot of information out there.

    The `reverb` effect is a port of the `reverb` effect from [SoX](http://sox.sourceforge.net/), which implements the freeverb algorithm. The `g2reverb` effect is a port of the g2reverb LADSPA plugin by Fons Adriaensen. It behaves similarly to the GVerb plugin, which used to be included with Audacity. There's a page on the [Audacity wiki](http://wiki.audacityteam.org/wiki/GVerb) which may be useful. Both reverb effects are rather simplistic, so if you want high-quality reverb, I would suggest looking for some reverb impulses and using them with the `zita_convolver` effect.

2. The `remix` effect is a bit confusing at first glance. Each channel selector specifies which channels to mix together into the output channel. Which output channel each channel selector represents is based on its position, not the numbers. For example, say you have 4 input channels. You can reverse the order of the channels like this `remix 3 2 1 0`. The first argument (which selects input channel 3) represents output channel 0, the second argument (which selects input channel 2) represents output channel 1, and so on.

    Using `remix -` mixes all input channels into a single output channel because `-` stands for "channel 0 through channel n-1", where n is the number of input channels. By default, however, `ladspa_dsp` is mono, so you have to set the number of input and output channels. See bug #12.

    If you want mono output, you can replace `<hw_device>` in the example configuration from the wiki to `monocard` if you've also included the lines you posted in your comment (with the `pcm.!default monocard` line removed). The other option is to put this in the effects chain: `remix 0,1 . mult 0.5`. This remixes channels 0 and 1 into the left channel and nothing into the right channel, then multiplies each sample by 0.5 to prevent clipping. Note that you will have to set the number of input and output channels to 2 for this to work.

3. For the LADSPA effect, FFmpeg support is only built if the `fir` and/or `zita_convolver` effects are being built **and** libsndfile is not available.

4. There is no way of doing that in my program currently and I don't have plans to implement it at this time (unless it's way easier to do than I think it is...). If there exists a LADSPA plugin that can do that type of processing, it would be easier to just use it in conjunction with my plugin instead of trying to re-implement its functionality.

**Comment by arjunmenon** [comment]
> I would recommend that you just look up how to use a parametric equalizer. There's quite a lot of information out there.

I looked up most of github and spent a lot of time getting values of preset through google.
Coudn't get much of it?

I just took values from [here](https://github.com/hongquan/nghongquan-quodlibet/blob/cb61a60a500c0b0fe058deddd12e14eb5ed9b2df/quodlibet/quodlibet/ext/events/equalizer.py#L32) and [here](http://advantage-bash.blogspot.com/2013/05/mplayer-presets.html) and [here](https://github.com/losogudok/mvc_audio_player/blob/538f9bd53862e6c9202d0552ea8d37ac09fdf307/src/js/consts.js#L56)

This is just some of it.

In the end
`effects_chain=gain 1.5 highpass 80 0.707 eq 20000 1.0 7.3 eq 10000 1.0 7.3 eq 5000 1.0 6.7 eq 3500 1.0 3.0 eq 2500 1.0 -3.0 eq 1750 1.0 -5.7 eq 1250 1.0 -6.6 eq 880 1.0 -14.7 eq 622 1.0 -16 eq 440 1.0 -11.2 eq 311 1.0 -10.5 eq 220 1.0 -8.5 eq 156 1.0 2.6 eq 100 1.0 2.6 eq 50 1.0 5.3`

This was preset for Rock.

Now this didn't work as imagined as the Q values are just arbitrary. That was expected.

So have you bookmarked any resources which helps out in getting values of EQ presets?
Since I did find many resources but none of them had Q values to refer to.

It would be much helpful.

**Comment by bmc0** [comment]
> So have you bookmarked any resources which helps out in getting values of EQ presets?

No, not really. I don't use the filters in that way. Also, some graphic EQs are FIR-based and cannot be replicated easily with biquads.

You could have a look through some of the presets provided with Peace (a GUI fontend for Equalizer APO): https://sourceforge.net/projects/peace-equalizer-apo-extension/files/Configurations%20%28presets%29/. The files are human-readable and frequencies, quality factors, and gains are provided. I can't say whether the presets will sound the way you want them to, but my code and Equalizer APO both use the same formulae for calculating the filter coefficients so the resulting response should be the same.

**Comment by arjunmenon** [comment]
Thank you. I will test them today.
