### ISSUE TITLE
Change effects chain on the fly?

### ISSUE THREAD

**Issue by ftab** [bmc0/dsp#19]
Just found this project. I really, really like the idea of the simple text based config and multi channel stuff. And you've got every effect I can think to use right now!

I'd like to use this to control all system sound. Is there a way to change the effects (or at least the values) on the fly (e.g. apply different EQs at different volume and/or speed levels, or have a user adjustable bass/mid/treble)?

Would like to try to get this into my Pi and use GPS or accelerometer (dead-reckoned) speed data to adjust it if I'm going faster.

**Comment by bmc0** [comment]
Unfortunately, it was not really designed to be dynamic. There's currently no way to change anything except by destroying and rebuilding the effects chain. With the CLI program, you can do this by pressing the 'e' key in interactive mode. With the LADSPA plugin, the host must call `cleanup()` and then `instantiate()` again. The problem with rebuilding the effects chain is that the filter states are not saved, so you tend to get clicks and/or other artifacts.
