### ISSUE TITLE
Global effects file?

### ISSUE THREAD

**Issue by laduke** [bmc0/dsp#2]
Hello,
Where would I put or how would I specify a global effects file (using alsa, no pulse). My mpd runs as user "mpd" and doesn't have a login shell...

**Comment by bmc0** [comment]
At the moment, the only way to do this is to set the `LADSPA_DSP_CONFIG` environment variable. A patch is in the works to make it load `/etc/ladspa_dsp/config` when loading `$XDG_CONFIG_HOME/ladspa_dsp/config` fails.

**Comment by bmc0** [comment]
Commit 6b1545f adds support for a global config file at `/etc/ladspa_dsp/config`. The default search paths are now (in order):
- `$XDG_CONFIG_HOME/ladspa_dsp/config`
- `$HOME/.config/ladspa_dsp/config` (if `$XDG_CONFIG_HOME` is not set)
- `/etc/ladspa_dsp/config`

**Comment by laduke** [comment]
Thanks. Got it working.
