### ISSUE TITLE
faled to load module

### ISSUE THREAD

**Issue by sandikata** [bmc0/dsp#26]
I'm still strugling with this thinks..
I did everything as mentioned.. but
dsp: gain: failed to parse gain: -5.0
dsp: error: failed to initialize effect: gain
E: [pulseaudio] module-ladspa-sink.c: Failed to instantiate plugin ladspa_dsp with label ladspa_dsp
E: [pulseaudio] module.c: Failed to load module "module-ladspa-sink" (argument: "sink_name=dsp plugin=ladspa_dsp label=ladspa_dsp"): initialization failed.
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.

it sais failed to parse gain: -5.0... and i cannot realize whats the problem.

└┌(%:~)┌- cat .config/ladspa_dsp/config 
effects_chain=gain -5.0 eq 50 1.7 4.2 eq 72 2.0 3.0 eq 95 2.0 -2.0 eq 135 1.5 -1.2 eq 205 1.0 0.3 eq 462 1.0 0.5 eq 1100 1.0 -4.1 eq 1692 1.0 -4.2 eq 2200 2.0 2.0 eq 3200 3.0 -4.5 eq 5000 4.0 -1.8 eq 7000 2.0 -2.5 eq 14300 1.0 -2.8

**Comment by bmc0** [comment]
The decimal separator is probably something other than a `.` for your locale. Add this line to your ladspa_dsp configuration file:

    LC_NUMERIC=C

See #5 and #24 for more info.

**Comment by sandikata** [comment]
LC_NUMERIC=C effects_chain=gain -5.0 eq 50 1.7 4.2 eq 72 2.0 3.0 eq 95 2.0 -2.0 eq 135 1.5 -1.2 eq 205 1.0 0.3 eq 462 1.0 0.5 eq 1100 1.0 -4.1 eq 1692 1.0 -4.2 eq 2200 2.0 2.0 eq 3200 3.0 -4.5 eq 5000 4.0 -1.8 eq 7000 2.0 -2.5 eq 14300 1.0 -2.8

?

**Comment by bmc0** [comment]
Yes, the contents should be this:

    LC_NUMERIC=C
    effects_chain=gain -5.0 eq 50 1.7 4.2 eq 72 2.0 3.0 eq 95 2.0 -2.0 eq 135 1.5 -1.2 eq 205 1.0 0.3 eq 462 1.0 0.5 eq 1100 1.0 -4.1 eq 1692 1.0 -4.2 eq 2200 2.0 2.0 eq 3200 3.0 -4.5 eq 5000 4.0 -1.8 eq 7000 2.0 -2.5 eq 14300 1.0 -2.8
