### ISSUE TITLE
pulseaudio module load failed

### ISSUE THREAD

**Issue by hansbert2000** [bmc0/dsp#27]
First, thanks for your work and providing a way to improve the sound under linux.

I downloaded the source code, compiled and installed it, this worked fine so far, but when i try to load the plugin in pulseaudio i get the error message "Module load failed".
I also tried to build the module with all and minimal dependencies, same problem.

```
$ pacmd load-module module-ladspa-sink sink_name=dsp master=alsa_output.pci-0000_00_1b.0.iec958-stereo plugin=ladspa_dsp label=ladspa_dsp
 Module load failed.
```

I am using arch linux kernel 4.14.19-1 and pulseaudio 11.1.

**Comment by hansbert2000** [comment]
Ok maybe i should have looked first into the closed issues list, adding LC_NUMERIC=C to the config fixes the problem. I think you should add a hint in the wiki page to avoid frustration.

**Comment by bmc0** [comment]
There is actually information about this in the [README](https://github.com/bmc0/dsp#configuration) and man page, but perhaps I should add it to the wiki page as well...
