### ISSUE TITLE
Can't get it to work with Debian Jessie 

### ISSUE THREAD

**Issue by ra-om** [bmc0/dsp#3]
> ~/.config/ladspa_dsp/config:
> effects_chain=gain -10.0 eq lowshelf 1000 0.9s 10.0

/.asoundrc:
pcm.dsp {
    type plug
    slave {
    format FLOAT
        rate unchanged
        channels unchanged
        pcm {
            type ladspa
            path "/usr/lib/ladspa"
            playback_plugins [{
                label "ladspa_dsp"
            }]
            slave.pcm {
                type plug
                slave {
                    pcm "hw:0"
                    rate unchanged
                    channels unchanged
                }
            }
        }
    }
}

pcm.!default {
    type copy
    slave.pcm "dsp"
}

Don't know how to keep spacing, I have the same one as the wiki

> ./configure:

[dsp] enabled sndfile.o (sndfile)
[dsp] disabled ffmpeg.o (libavcodec libavformat libavutil)
[dsp] enabled resample.o fir.o (fftw3)
[dsp] enabled alsa.o (alsa)
[dsp] disabled ao.o (ao)
[dsp] enabled mp3.o (mad)
[dsp] disabled pulse.o (libpulse-simple)
enabled ladspa_dsp
[ladspa_dsp] enabled fir.o (fftw3)
[ladspa_dsp] enabled sndfile.o (sndfile)
[ladspa_dsp] disabled ffmpeg.o (libavcodec libavformat libavutil)
[ladspa_dsp] enabled mp3.o (mad)

I added LADSPA_DSP_LOGLEVEL=VERBOSE in /etc/environment but don't know where to find the output file. 

Setting alsa apps output to either default or dsp produces no audible difference. 

On Audacious the dsp output option shows up as dsp ((null)) in the tab. Plays sound fine when selected but the config file seems to do nothing.

On VLC, dsp doesn't show up at all in the output device list.

What am I doing wrong?

**Comment by bmc0** [comment]
`~/.config/ladspa_dsp/config` is incorrect. It should be:

```
effects_chain=gain -10.0 lowshelf 1000 0.9s 10.0
```

It prints messages to stdout. Try running

```
$ LADSPA_DSP_LOGLEVEL=VERBOSE <program>
```

in a terminal emulator and look for lines prefixed with `ladspa_dsp:` or `dsp:`.

**Comment by ra-om** [comment]
This was entirely an issue on my end. You can safely dismiss my previous comment.
