### ISSUE TITLE
Can't handle decimal in dsp config file, Audacious and LMMS crash.

### ISSUE THREAD

**Issue by mzpsh** [bmc0/dsp#32]
Seems like dsp can't handle decimal in config file, even as simple as "-4.6".
Tried not to use decimal, like "-4" and it works, no more crash.
This affect gain and eq effect, haven't tried other effect.

This affect Audacious and LMMS, seems like other program is affected too.

Distro: Arch Linux
dsp version from AUR: latest from git
Audacious version: 3.9
LMMS version: 1.1.3

Terminal output of audacious:
```
ladspa_dsp: gain: failed to parse gain: -4.6
ladspa_dsp: error: failed to initialize effect: gain
Kerusakan segmentasi (core didump)
```
terminal output of lmms:
```
ladspa_dsp: gain: failed to parse gain: -4.6
ladspa_dsp: error: failed to initialize effect: gain
Kerusakan segmentasi (core didump)
```

My ~/.config/ladspa_dsp/config file:
`effects_chain=gain -4.6`

**Comment by mzpsh** [comment]
Just read the readme again. Sorry.

**Comment by bmc0** [comment]
Regarding the segfaults:

Audacious doesn't check the return value of `instantiate()` like it should ([code here](https://github.com/audacious-media-player/audacious-plugins/blob/master/src/ladspa/effect.cc#L61)), so it crashes if `instantiate()` fails (NULL pointer dereference).

I'm not quite sure why LMMS crashes. Maybe it calls `cleanup()` even when `instantiate()` fails? I haven't really had a proper look at the code.

**Comment by mzpsh** [comment]
BTW, I moved to a new system, and not putting LC_NUMERIC option.
