### ISSUE TITLE
Splitting channels

### ISSUE THREAD

**Issue by Ape** [bmc0/dsp#36]
I would like to split a channel into two using a frequency crossover. Then I would like to do different `ladspa_host` filters two those two channels. Finally I would combine the halves back together. Is this possible?

**Comment by bmc0** [comment]
Yes, it's possible. The effects chain should look something like this (assuming a mono input and using a 1st order crossover at 200Hz):

```
# Duplicate channel 0
remix 0 0
# LF effects
:0 lowpass_1 200 ladspa_host <params> :
# HF effects
:1 highpass_1 200 ladspa_host <params> :
# Combine channel 0 and 1
remix 0,1
```

**Comment by Ape** [comment]
Thank you.
