### ISSUE TITLE
Convolution performance

### ISSUE THREAD

**Issue by kalle-del-haye** [bmc0/dsp#4]
Good to see a DSP and convolution LADSPA-plugin!

To this time I'm doing Digital Room Correction and speaker management for my 8 channel system with the help of Jackd. And its a pain to get any Alsa program to work easy and reliable.

Building your program and get it to work without bigger issues. I tested the `fir` effect with a filter impulse generated by [DRC](http://drc-fir.sourceforge.net/) in stereo mode and get a latency of more than 2 seconds. Which is not really usable for any audio/video playback.

So, do you planning to improve the performance of your convolution filter in the near future?

The most powerful convolver i know is [Jconvolver](http://kokkinizita.linuxaudio.org/linuxaudio/index.html) - very fast and easy to configure. Maybe using the [zita-convolver](http://kokkinizita.linuxaudio.org/linuxaudio/downloads/zita-convolver-3.1.0.tar.bz2) library is an option for you? It's available on many Linux distributions, for example Ubuntu in my case. An interesting project using this library is [Folve](https://github.com/hzeller/folve) - which combines it with fuse.

**Comment by bmc0** [comment]
The `fir` effect currently does not do partitioned convolution, so the latency is equal to the number of samples in the filter kernel. I've been thinking about rewriting the effect for a while, but I haven't gotten around to it yet. Anyway, I'll look into it, but I can't give you an expected completion date at the moment.

**Comment by kalle-del-haye** [comment]
Thanks for replying.
So, I will keep an eye on your project and test it whenever you finished it.

The special about the zita-convolver, mentioned above, is the use of different sized partitions. And because of this it can operate in real-time. The [IR-LV2](https://github.com/Anchakor/ir.lv2) is an interesting convolution plug-in for LV2 hosts using the zita-convolver library.

**Comment by bmc0** [comment]
The `fir` effect now does non-uniform partitioned convolution. It does not currently do zero latency convolution (I have not had time to work out the best way implement that yet), but it is capable of single sample latency if you set the minimum partition length to 1.

**Comment by PkmX** [comment]
It seems partitioned convolution has been reverted by 801d43419be1b0faf2f6a303ea78353f88b2f494 some months ago, so we are going back to high latency again. Maybe this issue should be re-opened until it is fixed?

This effect is what I primary use dsp for (via pulse/ladspa), but with the latency it is completely unsuitable for anything interactive for now.

**Comment by bmc0** [comment]
Good point, I'll re-open this issue.

I do fully intend to fix this, but haven't gotten around to it yet.

**Comment by bmc0** [comment]
Commit ba4c446 on the unstable branch adds the `zita_convolver` effect, which does partitioned convolution via the the zita-convolver library by Fons Adriaensen. It is not very well tested at this point, but it should be usable.

The minimum latency is 64 samples (1.45ms at 44.1kHz). I'll look into making it do zero latency later, but it'll take a bit of work.

**Comment by PkmX** [comment]
I just tested `zita_convolver` with my own impulse file and it seems to be working great! The latency is low enough for interactive usage (gaming) and it also seems to be void of the clipping sound that was produced from `fir`. Props for a quick fix!

**Comment by bmc0** [comment]
The `zita_convolver` effect appears to be working fully now (and is in the master branch), so I'm going to re-close this issue.
