### ISSUE TITLE
Can't get ladsp working on Ubuntu

### ISSUE THREAD

**Issue by chaseemory** [bmc0/dsp#40]
I followed the instructions on the main page to install ladsp and configured my default devices, but when I try to play audio through chromium i get this error

> ladspa_dsp: error: no config files found
ALSA lib pcm_ladspa.c:1509:(snd_pcm_ladspa_add_plugin) Unable to find or load plugin 'ladspa_dsp' ID 0, path '/usr/lib/ladspa'
ladspa_dsp: error: no config files found
ALSA lib pcm_ladspa.c:1509:(snd_pcm_ladspa_add_plugin) Unable to find or load plugin 'ladspa_dsp' ID 0, path '/usr/lib/ladspa'

my ./configure looks like this

> enabled dsp
[dsp] disabled ladspa_host.o
[dsp] disabled sndfile.o (sndfile)
[dsp] disabled ffmpeg.o (libavcodec libavformat libavutil)
[dsp] disabled resample.o fir.o (fftw3)
[dsp] disabled zita_convolver.o
[dsp] enabled alsa.o (alsa)
[dsp] disabled ao.o (ao)
[dsp] disabled mp3.o (mad)
[dsp] disabled pulse.o (libpulse-simple)
enabled ladspa_dsp
[ladspa_dsp] disabled ladspa_host.o
[ladspa_dsp] disabled fir.o (fftw3)
[ladspa_dsp] disabled zita_convolver.o

my ~/.config/ladsp_dsp/config looks like this

> effects_chain=gain -8.0 lowshelf 97.0 0.9s 7.5 eq 380 2.000 0.6 eq 1000 1.500 -1.5 eq 2100 0.300 6.0 eq 2800 3.000 -1.5 eq 3340 5.000 1.1 eq 4000 6.000 -1.2 eq 5450 6.000 -5.1 eq 6200 9.000 -2.2 eq 7800 9.000 -2.0

and my .asoundrc looks like this

> pcm.dsp {
	type plug
	slave {
		format FLOAT
		rate unchanged
		channels unchanged
		pcm {
			type ladspa
			path "/usr/lib/ladspa"
			playback_plugins [{
				label "ladspa_dsp"
			}]
			slave.pcm {
				type plug
				slave {
					pcm "hw:1"
					rate unchanged
					channels unchanged
				}
			}
		}
	}
}
pcm.!default {
	type copy
	slave.pcm "dsp"
}

my aplay -l looks like this, and I am trying to use the Gungnir Gen 5 USB

> **** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC1150 Analog [ALC1150 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 1: ALC1150 Digital [ALC1150 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: G5 [Gungnir Gen 5], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

any help would be appreciated :)

**Comment by bmc0** [comment]
> ~/.config/ladsp_dsp/config

Is this path a typo? It should be `~/.config/ladspa_dsp/config`.

**Comment by chaseemory** [comment]
Well, I feel dumb, it was a typo, on my part when I made that directory, I had even made the one in /etc trying to figure out why it wasnt working, but I mistyped that one as well. -_-

Thank you for the help! It is working exactly as I hoped it would now.

**Comment by bmc0** [comment]
Alright, glad to hear it works now.
