### ISSUE TITLE
 Failed to load module

### ISSUE THREAD

**Issue by pit65** [bmc0/dsp#48]
Hi

For me full path can not help.
Compile with ladspa 1.15 and pulseaudio 9 on Slackware distro.

I: [pulseaudio] module.c: Loaded "module-filter-heuristics" (index: #22; argument: "").
I: [pulseaudio] module.c: Loaded "module-filter-apply" (index: #23; argument: "").
E: [pulseaudio] module-ladspa-sink.c: Failed to parse module arguments.
E: [pulseaudio] module.c: Failed to load module "module-ladspa-sink" (argument: "sink_name=dsp master=alsa_output.pci-0000_00_1b.0.analog-stereo plugin=ladspa_dsp label=ladspa_dsp set-default-sink dsp"): initialization failed.
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Zainicjowanie usługi się nie powiodło.
I: [pulseaudio] module.c: Unloading "module-filter-apply" (index: #23).
I: [pulseaudio] module.c: Unloaded "module-filter-apply" (index: #23).

Distro Slackware64

**Comment by bmc0** [comment]
The `set-default-sink dsp` command needs to be on its own line after the `load-module ...` command.
