### ISSUE TITLE
crossfeed usage example

### ISSUE THREAD

**Issue by CamilleScholtz** [bmc0/dsp#50]
I have set up an effects chain with filters to change the gain, however I am lost as to how I should add crossfeed, an example would be really helpful. This for example does not work:

```
crossfeed 100 1 gain -9.0 lowshelf 110 0.9s 9.0 eq 250 1.0 -0.3 eq 480 2.5 0.45 eq 810 2.5 -0.95 eq 1250 2.5 -1.0 eq 2100 2.5 1.5 eq 2550 3.0 -1.6 eq 4060 2.0 7.0 eq 6050 7.0 -1.65 eq 8000 7.0 -1.7
```

**Comment by bmc0** [comment]
`f0` should generally be somewhere between 600-750Hz and `separation` should be 3dB or greater. A good setting to try is `crossfeed 700 4.5`. If it sounds too narrow/monophonic, increase the `separation` parameter.

Note that if you're using the LADSPA plugin, you need to configure it for stereo operation. See my comment in #12.

**Comment by CamilleScholtz** [comment]
Thanks!
