### ISSUE TITLE
No function after installation (Mint 19)

### ISSUE THREAD

**Issue by fbittmann** [bmc0/dsp#55]
Hello, I would like to DSP as a system wide equalizer on my Linux Mint 19.3 x64 machine. However, there is no functionality after installation. What I did was the following, output provided.

Installed dependencies, cloned the folder to my disc.

*sudo ./configure*
enabled dsp
[dsp] disabled ladspa_host.o
[dsp] disabled sndfile.o (sndfile)
[dsp] disabled ffmpeg.o (libavcodec libavformat libavutil)
[dsp] disabled resample.o fir.o fir_p.o (fftw3)
[dsp] disabled zita_convolver.o
[dsp] enabled alsa.o (alsa)
[dsp] disabled ao.o (ao)
[dsp] disabled mp3.o (mad)
[dsp] disabled pulse.o (libpulse-simple)
enabled ladspa_dsp
[ladspa_dsp] disabled ladspa_host.o
[ladspa_dsp] disabled fir.o fir_p.o (fftw3)
[ladspa_dsp] disabled zita_convolver.o

*sudo make install*
cc -c -o obj/dsp/dsp.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   dsp.c
cc -c -o obj/dsp/effect.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   effect.c
cc -c -o obj/dsp/codec.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   codec.c
cc -c -o obj/dsp/sampleconv.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   sampleconv.c
cc -c -o obj/dsp/util.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   util.c
cc -c -o obj/dsp/biquad.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   biquad.c
cc -c -o obj/dsp/gain.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   gain.c
cc -c -o obj/dsp/crossfeed.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   crossfeed.c
cc -c -o obj/dsp/remix.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   remix.c
cc -c -o obj/dsp/st2ms.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   st2ms.c
cc -c -o obj/dsp/delay.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   delay.c
cc -c -o obj/dsp/noise.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   noise.c
cc -c -o obj/dsp/stats.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   stats.c
cc -c -o obj/dsp/null.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   null.c
cc -c -o obj/dsp/sgen.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   sgen.c
cc -c -o obj/dsp/pcm.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   pcm.c
cc -c -o obj/dsp/alsa.o -MMD -MP -Os -Wall -std=gnu99 -DHAVE_ALSA -I/usr/include/alsa   alsa.c
cc -o dsp   obj/dsp/dsp.o obj/dsp/effect.o obj/dsp/codec.o obj/dsp/sampleconv.o obj/dsp/util.o obj/dsp/biquad.o obj/dsp/gain.o obj/dsp/crossfeed.o obj/dsp/remix.o obj/dsp/st2ms.o obj/dsp/delay.o obj/dsp/noise.o obj/dsp/stats.o obj/dsp/null.o obj/dsp/sgen.o obj/dsp/pcm.o obj/dsp/alsa.o -lasound -lm
install -Dm755 dsp /usr/bin/dsp
cc -c -o obj/ladspa_dsp/ladspa_dsp.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    ladspa_dsp.c
cc -c -o obj/ladspa_dsp/effect.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    effect.c
cc -c -o obj/ladspa_dsp/util.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    util.c
cc -c -o obj/ladspa_dsp/biquad.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    biquad.c
cc -c -o obj/ladspa_dsp/gain.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    gain.c
cc -c -o obj/ladspa_dsp/crossfeed.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    crossfeed.c
cc -c -o obj/ladspa_dsp/remix.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    remix.c
cc -c -o obj/ladspa_dsp/st2ms.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    st2ms.c
cc -c -o obj/ladspa_dsp/delay.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    delay.c
cc -c -o obj/ladspa_dsp/noise.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    noise.c
cc -c -o obj/ladspa_dsp/stats.o -MMD -MP -Os -Wall -std=gnu99 -fPIC -DPIC -DLADSPA_FRONTEND -DSYMMETRIC_IO    stats.c
cc -o ladspa_dsp.so  -shared -fPIC  obj/ladspa_dsp/ladspa_dsp.o obj/ladspa_dsp/effect.o obj/ladspa_dsp/util.o obj/ladspa_dsp/biquad.o obj/ladspa_dsp/gain.o obj/ladspa_dsp/crossfeed.o obj/ladspa_dsp/remix.o obj/ladspa_dsp/st2ms.o obj/ladspa_dsp/delay.o obj/ladspa_dsp/noise.o obj/ladspa_dsp/stats.o  -lm -lc
install -Dm755 ladspa_dsp.so /usr/lib/ladspa/ladspa_dsp.so
install -Dm644 dsp.1 /usr/share/man/man1/dsp.1

The installation works partly, so the software is found. But it does not work.
(Flac file is actually called that...)
*dsp lol.flac -ot alsa -e s24_3 hw:2 lowshelf 60 0.5 +4.0^C*
dsp: error: failed to open input: lol.flac

*echo $XDG_CONFIG_HOME*
Gives an empty output.

Apparently, there were no folders created at all during install. I cannot find any of the following:
$HOME/.config/ladspa_dsp/config
/etc/ladspa_dsp/config
~/.asoundrc

Sorry, I have no idea what is going on here. Any help is appreciated. Thanks.

**Comment by bmc0** [comment]
The cli program requires either libsndfile or ffmpeg to read anything other than raw PCM. Assuming the package name is the same as in Debian, you should install `libsndfile1-dev`.

`$XDG_CONFIG_HOME` is usually unset and defaults to `$HOME/.config`.

You must create `~/.config/ladspa_dsp/config` and `~/.asoundrc` (see README.md and [this wiki page](https://github.com/bmc0/dsp/wiki/System-Wide-DSP-Guide) for more information).

**Comment by fbittmann** [comment]
Hey and thanks for the info. I am sorry, I thought these are created during the installation. That is why I thought something went wrong. I played around with it and now the EQ works. Really neat, thanks a lot. Issue resolved.
