### ISSUE TITLE
Sample rate not honored with LADSPA DSP plugin

### ISSUE THREAD

**Issue by cepamoi** [bmc0/dsp#58]
Hello,

I use DSP with the LADSPA plugin with PulseAudio on Ubuntu 20.04.
I recompiled PulseAudio applying a patch to be able to set "avoid-resampling = yes" in the /etc/pulse/daemon.conf config file. See here: [https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1081](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1081)
And the original issue here: [https://github.com/bmc0/dsp/issues/56](https://github.com/bmc0/dsp/issues/56)

When I start the playback on the PulseAudio default sink, the sample rate is automatically adjusted to the audio file. This is expected as I set "avoid-resampling = yes".
But when I start the playback on the LADSPA DSP sink, the sample rate remains the same as the one in the PulseAudio default sink when I loaded the LADSPA DSP plugin. The sample rate is not adjusted to the audio file.

I'm not sure this is an issue with DSP or with LADSPA or with PulseAudio.
Do you have any idea?

Thanks.

**Comment by bmc0** [comment]
LADSPA plugins have no control over the sample rate. The host (PulseAudio in this case) is responsible for setting and changing it. See #10.
