### ISSUE TITLE
Support for multiple different ladspa configurations

### ISSUE THREAD

**Issue by Ape** [bmc0/dsp#6]
I'd like to have multiple ladspa sinks with different effect chains. This might be already possible with some multichannel trickery, but separate sinks would be better.

**Comment by bmc0** [comment]
I apologize for the long delay. I had time to implement this earlier today (commit 01eba02 in the unstable branch). See the [readme](https://github.com/bmc0/dsp/tree/unstable#configuration) for details. Let me know if this works for you.

**Comment by Ape** [comment]
Yes, this works just like I wanted. Thanks.
