### ISSUE TITLE
Requesting clarification on ladspa-sdk dependency

### ISSUE THREAD

**Issue by N-R-K** [bmc0/dsp#68]
Hi, thanks for the software. I have a couple questions regarding the ladspa-sdk dependency.

For some context, I only want to have a minimal build so that I can use parametric eq with ALSA. I followed the [wiki instructions](https://github.com/bmc0/dsp/wiki/System-Wide-DSP-Guide) and used the following:

```console
$ ./configure --disable-dsp --disable-fftw3 --disable-zita-convolver
```

This requires `ladspa-sdk` to build due to the `<ladspa.h>` header include. But I noticed that the produced `ladspa_dsp.so` doesn't seem to link against anything from it.

So my question is: is it okay to get `ladspa_dsp.so` built by vendoring that header file but without having any of the libraries provided by `ladspa-sdk` installed in my system? Or will it lead to problems?

**Comment by richardpl** [comment]
ladspa is single .h header, last time i checked.

**Comment by N-R-K** [comment]
> ladspa is single .h header, last time i checked.

The `ladspa-sdk` package also installs some dynamic libraries. So far everything is working fine without those, so I'm assuming those "plugins" aren't needed by `dsp`. Asking the author just to be sure.

**Comment by richardpl** [comment]
Ah, yes those are helpers, like listing of installed ladspa plugins in some paths and similar, imho not needed at all, header is only needed for developing hosts and plugins...

**Comment by bmc0** [comment]
@richardpl is correct. Nothing in the `ladspa-sdk` package is required at run time.
